# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
public/openapi.json:
  info-license:
    - '#/info'
  struct:
    - '#/components/schemas/ComicDTO/properties/author/nullable'
    - '#/components/schemas/ComicDTO/properties/coverUrl/nullable'
    - '#/components/schemas/ComicDTO/properties/year/nullable'
    - '#/components/schemas/ComicDTO/properties/series/nullable'
    - '#/components/schemas/ComicUpdateSchema/properties/series/nullable'
    - '#/components/schemas/ComicUpdateSchema/properties/issue/nullable'
    - '#/components/schemas/ComicUpdateSchema/properties/year/nullable'
    - '#/components/schemas/ComicUpdateSchema/properties/tags/nullable'
    - '#/components/schemas/ComicUpdateSchema/properties/coverUrl/nullable'
    - '#/components/schemas/ComicUpdateSchema/properties/comicVineId/nullable'
    - '#/components/schemas/CollectionDTO/properties/description/nullable'
    - '#/components/schemas/BookmarkDTO/properties/note/nullable'
    - '#/components/schemas/BookmarkCreateSchema/properties/note/nullable'
    - '#/components/schemas/FriendDTO/properties/name/nullable'
    - '#/components/schemas/FriendDTO/properties/email/nullable'
    - '#/components/schemas/FriendDTO/properties/image/nullable'
    - '#/components/schemas/UserProfileUpdateSchema/properties/image/nullable'
  security-defined:
    - '#/paths/~1auth~1register/post'
    - '#/paths/~1library/get'
    - '#/paths/~1library~1upload/post'
    - '#/paths/~1comics~1{id}/get'
    - '#/paths/~1comics~1{id}/delete'
    - '#/paths/~1comics~1{id}/patch'
    - '#/paths/~1comics~1{id}~1progress/put'
    - '#/paths/~1collections/get'
    - '#/paths/~1collections/post'
    - '#/paths/~1bookmarks/get'
    - '#/paths/~1bookmarks/post'
    - '#/paths/~1bookmarks/delete'
    - '#/paths/~1collections~1{id}/get'
    - '#/paths/~1collections~1{id}/delete'
    - '#/paths/~1collections~1{id}/patch'
    - '#/paths/~1collections~1{id}~1items/post'
    - '#/paths/~1collections~1{id}~1items/delete'
    - '#/paths/~1comics~1{id}~1download/get'
    - '#/paths/~1comics~1{id}~1enrich/get'
    - '#/paths/~1comics~1{id}~1favorite/post'
    - '#/paths/~1comics~1{id}~1favorite/delete'
    - '#/paths/~1comics~1search-metadata/get'
    - '#/paths/~1friends/get'
    - '#/paths/~1friends/delete'
    - '#/paths/~1friends~1invite/post'
    - '#/paths/~1friends~1requests/get'
    - '#/paths/~1friends~1requests/post'
    - '#/paths/~1friends~1requests~1{id}/put'
    - '#/paths/~1library~1{id}/delete'
    - '#/paths/~1user~1profile/patch'
