/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope & { 
  __WB_MANIFEST: Array<{ url: string; revision: string | null }> | undefined 
};

clientsClaim();

// ── Precaching ──────────────────────────────────────────────────────────────
// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// ── Static Assets (Images, Fonts) ───────────────────────────────────────────
registerRoute(
  ({ request }) => 
    request.destination === 'image' || 
    request.destination === 'font',
  new CacheFirst({
    cacheName: 'comet-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// ── API Routes (General) ────────────────────────────────────────────────────
// Most API routes should prefer the network but fallback to a stale cache
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') && !url.pathname.includes('/progress'),
  new NetworkFirst({
    cacheName: 'comet-api',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60, // 24 Hours
      }),
    ],
  })
);

// ── Reading Progress (Background Sync) ──────────────────────────────────────
// Queue failed progress updates to be retried when the user comes back online
const progressSyncPlugin = new BackgroundSyncPlugin('reading-progress-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours (in minutes)
});

registerRoute(
  ({ url }) => url.pathname.includes('/progress'),
  new NetworkFirst({
    cacheName: 'progress-sync',
    plugins: [progressSyncPlugin],
  }),
  'PUT'
);

// ── Helper: Manual Activation ────────────────────────────────────────────────
// Listen for the "SKIP_WAITING" message from the main thread to activate the new SW
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
